services:
  api:
    build:
      context: ./backend/.
      dockerfile: Dockerfile

    # image: ghcr.io/aryankumarofficial/secure-stack:latest
    restart: unless-stopped
    ports:
      - "5000:5000"

    env_file: ./backend/.env
    environment:
      NODE_ENV: production
  # web:
  #   build:
  #     context: ./web
  #     dockerfile: Dockerfile
  #   image: ghcr.io/<org>/myapp-web:latest
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   env_file: ./web/.env
  #   depends_on:
  #     - backend
